name: Build

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ~1.23.0
      - name: Build
        run: go build -ldflags "-H=windowsgui" -o komorebit.exe .
      - name: Zip
        run: Compress-Archive -Path .\komorebit.exe -DestinationPath .\komorebit-${{ github.event.release.tag_name }}.zip
        shell: pwsh
      - name: Upload release asset
        run: gh release upload --clobber ${{ github.event.release.tag_name }} .\komorebit-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
